// export const ActionType = {
//   SET_PRODUCTS: "SET_PRODUCTS",
//   GET_PRODUCTS_BY_ID: "GET_PRODUCTS_BY_ID",
//   REMOVE_PRODUCTS_BY_ID: "REMOVE_PRODUCTS_BY_ID",
//   SET_CATEGORY: "SET_CATEGORY",
// };

export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";
export const REMOVE_PRODUCTS_BY_ID = "REMOVE_PRODUCTS_BY_ID";
export const SET_CATEGORY = "SET_CATEGORY";

export const INSERT_PRODUCTS = "INSERT_PRODUCTS";
